version: "2"

services:
  dev:
    environment:
      TEXLIVE_IMAGE: quay.io/sharelatex/texlive-full:2017.1
      TEXLIVE_IMAGE_USER: root
      SHARELATEX_CONFIG: /app/config/settings.defaults.coffee
      DOCKER_RUNNER: "true"
      COMPILES_HOST_DIR: $PWD/compiles
      SYNCTEX_BIN_HOST_PATH: $PWD/bin/synctex
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compiles:/app/compiles
      
  ci:
    environment:
      TEXLIVE_IMAGE: quay.io/sharelatex/texlive-full:2017.1
      TEXLIVE_IMAGE_USER: root
      SHARELATEX_CONFIG: /app/config/settings.defaults.coffee
      DOCKER_RUNNER: "true"
      COMPILES_HOST_DIR: $PWD/compiles
      SYNCTEX_BIN_HOST_PATH: $PWD/bin/synctex
      SQLITE_PATH: /app/compiles/db.sqlite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./compiles:/app/compiles